UPDATE `access_requirement` SET `level_min`=25 WHERE `mapId`=47 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=25 WHERE `mapId`=349 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=33 WHERE `mapId`=289 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=35 WHERE `mapId`=129 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=31 WHERE `mapId`=429 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=39 WHERE `mapId`=209 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=37 WHERE `mapId`=329 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=45, `comment`='Sunken Temple' WHERE `mapId`=109 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=42, `comment`='Blackrock Depths' WHERE `mapId`=230 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=48, `comment`='Blackrock Spire' WHERE `mapId`=229 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=10 WHERE `mapId`=389 AND `difficulty`=0;
UPDATE `access_requirement` SET `comment`='Wailing Caverns' WHERE `mapId`=43 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=11 WHERE `mapId`=33 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=15 WHERE `mapId`=48 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=19 WHERE `mapId`=90 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=65 WHERE `mapId`=552 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=65 WHERE `mapId`=553 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=65 WHERE `mapId`=554 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=65, `comment`='Black Morass (Entrance)' WHERE `mapId`=269 AND `difficulty`=0;
UPDATE `access_requirement` SET `comment`='Black Morass (Entrance)' WHERE `mapId`=269 AND `difficulty`=1;
UPDATE `access_requirement` SET `level_min`=65 WHERE `mapId`=545 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=65 WHERE `mapId`=540 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=63 WHERE `mapId`=556 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=63, `comment`='Old Hillsbrad Foothills (Entrance)' WHERE `mapId`=560 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=62 WHERE `mapId`=558 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=61 WHERE `mapId`=557 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=60 WHERE `mapId`=546 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=59 WHERE `mapId`=547 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=58 WHERE `mapId`=542 AND `difficulty`=0;
UPDATE `access_requirement` SET `level_min`=57 WHERE `mapId`=543 AND `difficulty`=0;