REPLACE INTO `achievement_reward` (`entry`, `title_A`, `title_H`, `item`, `sender`, `subject`, `text`) VALUES 
(5866, 0, 0, 69213, 52135, 'A Gift from the Arch Druid', 'Never again will Hyjal shudder beneath the endless forces of flame. Never again shall the mortal races of the world tremble before the minions of Ragnaros. Now, thanks to your efforts, they will tremble before US. Your heroism on the Molten Front has been instrumental in the fight against the Firelord. You have gathered allies from all over Kalimdor and turned them into an army. You have fought the minions of Ragnaros... and prevailed. And for that, you have our deepest thanks.'),
(5449, 0, 0, 60869, 34337, 'Recovered item', 'We recovered a lost item in the twisting nether and noted that it was yours. Please find said object enclosed.'),
(5860, 0, 0, 69838, 40578, 'Please... Just Take It', 'Ever since his brother was taken away. This little creature has been nothing short of a handful. The guardians and I have done everything we can to contain his energy, but our efforts have fallen depressingly short. It is now clear. He wants to be with his brother. It took us nearly an hour to get him contained. Please, take him with you. Perhaps some time outside of this cavern will do him good.');


REPLACE INTO `locales_achievement_reward` (`entry`, `subject_loc1`, `subject_loc2`, `subject_loc3`, `subject_loc4`, `subject_loc5`, `subject_loc6`, `subject_loc7`, `subject_loc8`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) VALUES 
(5866, '', '', '', '', '', '', '', 'Дар верховного друида', '', '', '', '', '', '', '', 'Никогда больше Хиджал не ощутит на себе бескрайнюю силу легионов огня. Никогда больше смертные расы не склонятся перед слугами Рагнароса. Благодаря тебе они будут трепетать услышав НАШИ имена.Твоя отвага помогла нам низвергнуть Повелителя огня. Именно ты собра армию могущественных союзников со всего Калимдора. ВЫ сразились со слугами Рагнароса и... победили. Прими нашу искреннюю благодарность.'),
(5449, '', '', '', '', '', '', '', 'Найденная вещь', '', '', '', '', '', '', '', 'Мы нашли это посреди Круговерти Пустоты. Кажется, вещичка ваша. Прилагаем к письму посылку.'),
(5860, '', '', '', '', '', '', '', 'Просто возьми это, пожалуйста', '', '', '', '', '', '', '', 'Этот малыш совсем отбился от рук с тех пор, как его разлучили с братом. Мы со стражниками изо всех сил пытались его удержать, но все бесполезно: он хочет только одного - снова увидеть своего кровника. Знал(а) бы ты, сколько усилий потребовалось на то, чтобы его упаковать! Забери его, ради всего святого. Возможно, за пределами пещеры он немного успокоится.');
