ALTER TABLE `instance_encounters`
	ADD COLUMN `difficulty` SMALLINT(5) NOT NULL DEFAULT '-1' AFTER `entry`,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`entry`, `difficulty`);

INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1340, 0, 54968, 0, 0, 'Asira Dawnslayer');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1339, 0, 54938, 439, 0, 'Archbishop Benedictus');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1337, 0, 54590, 0, 0, 'Arcurion'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1332, 0, 55869, 0, 0, 'Alizabal'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1299, 1, 111533, 447, 0, 'Madness of Deathwing'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1298, 0, 56427, 0, 0, 'Warmaster Blackhorn'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1297, 0, 55294, 0, 0, 'Ultraxion'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1296, 0, 55689, 0, 0, 'Hagara the Stormbinder'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1295, 0, 55312, 0, 0, 'Yor\'sahj the Unsleeping'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1294, 0, 55308, 0, 0, 'Warlord Zon\'ozz'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1292, 0, 55265, 0, 0, 'Morchok'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1291, 1, 104574, 0, 0, 'Spine of Deathwing');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1274, 1, 105576, 437, 0, 'Mannoroth'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1273, 0, 54853, 0, 0, 'Queen Azshara'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1272, 0, 55085, 0, 0, 'Peroth\'arn'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1271, 1, 110158, 435, 0, 'Murozond'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1269, 1, 72959, 0, 0, 'First Echo'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1268, 1, 72959, 0, 0, 'Second Echo');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1250, 0, 52363, 0, 0, 'Occu\'thar');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1206, 0, 52530, 0, 0, 'Alysrazor');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1205, 0, 53691, 0, 0, 'Shannox'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1204, 0, 52558, 0, 0, 'Lord Rhyolith'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1203, 1, 102237, 361, 0, 'Ragnaros'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1200, 1, 53494, 0, 0, 'Baleroc'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1197, 0, 52498, 0, 0, 'Beth\'tilac'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1194, 0, 23863, 340, 0, 'Daakara'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1193, 0, 24239, 0, 0, 'Hex Lord Malacrass');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1192, 0, 23577, 0, 0, 'Halazzi');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1191, 0, 23578, 0, 0, 'Jan\'alai'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1190, 0, 23576, 0, 0, 'Nalorakk'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1189, 0, 23574, 0, 0, 'Akil\'zon'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1188, 1, 72959, 0, 0, 'Edge of Madness'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1185, 0, 52571, 0, 0, 'Majordomo Staghelm'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1182, 0, 52148, 0, 0, 'Jin\'do the Godbreaker'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1181, 0, 52053, 0, 0, 'Zanzil');  
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1180, 0, 52059, 0, 0, 'High Priestess Kilnara');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1179, 0, 52151, 0, 0, 'Bloodlord Mandokir'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1178, 0, 52155, 0, 0, 'High Priest Venoxis'); 
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1036, 0, 39705, 303, 0, 'Ascendant Lord Obsidius');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1036, 0, 39705, 323, 1, 'Ascendant Lord Obsidius');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1037, 0, 39700, 0, -1, 'Beauty');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1038, 0, 39679, 0, -1, 'Corla, Herald of Twilight');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1039, 0, 39698, 0, -1, 'Karsh Steelbender');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1040, 0, 39665, 0, -1, 'Rom\'ogg Bonecrusher');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1041, 0, 43873, 0, -1, 'Altairus');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1042, 0, 43875, 311, 0, 'Asaad');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1042, 0, 43875, 319, 1, 'Asaad');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1043, 0, 43878, 0, -1, 'Grand Vizier Erthan');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1044, 0, 40765, 0, -1, 'Commander Ulthok');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1045, 0, 40586, 0, -1, 'Lady Naz\'jar');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1046, 0, 40788, 0, -1, 'Mindbender Ghur\'sha');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1047, 1, 72959, 302, 0, 'Ozumat');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1047, 1, 72959, 324, 1, 'Ozumat');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1048, 0, 40319, 0, -1, 'Drahga Shadowburner');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1049, 0, 40484, 304, 0, 'Erudax');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1049, 0, 40484, 322, 1, 'Erudax');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1050, 0, 40177, 0, -1, 'Forgemaster Throngus');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1051, 0, 39625, 0, -1, 'General Umbriss');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1052, 0, 44577, 0, -1, 'General Husam');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1053, 0, 43612, 0, -1, 'High Prophet Barim');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1054, 0, 43614, 0, -1, 'Lockmaw');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1055, 0, 44819, 312, 0, 'Siamat');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1055, 0, 44819, 325, 1, 'Siamat');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1056, 0, 43438, 0, -1, 'Corborus');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1057, 0, 42333, 307, 0, 'High Priestess Azil');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1057, 0, 42333, 320, 1, 'High Priestess Azil');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1058, 0, 42188, 0, -1, 'Ozruk');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1059, 0, 43214, 0, -1, 'Slabhide');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1060, 0, 47739, 6, 0, 'Captain Cookie');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1062, 0, 47626, 0, -1, 'Admiral Ripsnarl');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1063, 0, 43778, 0, -1, 'Foe Reaper 5000');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1064, 0, 47162, 0, -1, 'Glubtok');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1065, 0, 47296, 0, -1, 'Helix Gearbreaker');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1069, 0, 46962, 0, -1, 'Baron Ashbery');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1070, 0, 3887, 0, -1, 'Baron Silverlaine');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1071, 0, 4278, 0, -1, 'Commander Springvale');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1072, 0, 46964, 8, 0, 'Lord Godfrey');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1072, 0, 46964, 327, 1, 'Lord Godfrey');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1073, 0, 46963, 0, -1, 'Lord Valden');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1074, 0, 39731, 0, -1, 'Ammunae');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1075, 0, 39788, 0, -1, 'Anraphet');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1076, 0, 39428, 0, -1, 'Earthrager Ptah');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1077, 0, 39587, 0, -1, 'Isiset');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1078, 0, 39378, 305, 0, 'Rajh');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1078, 0, 39378, 321, 1, 'Rajh');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1079, 0, 39732, 0, -1, 'Setesh');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1080, 0, 39425, 0, -1, 'Temple Guadrian Anhuur');
INSERT INTO `instance_encounters` (`entry`, `creditType`, `creditEntry`, `lastEncounterDungeon`, `difficulty`, `comment`) VALUES (1081, 0, 49541, 326, 1, 'Vanessa VanCleef');



