INSERT IGNORE INTO `disables` VALUES ('4', '3922', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '3923', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '3924', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4240', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4244', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4768', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4769', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4770', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4771', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4772', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4773', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4774', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4775', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4776', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4777', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4778', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4779', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4780', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4781', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4782', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4783', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4784', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4785', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '4786', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '5258', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '6803', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '6835', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7177', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7178', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7179', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7180', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7231', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7264', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7265', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7315', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7316', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7317', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7318', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7319', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7320', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7321', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7322', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7323', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7324', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7325', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7326', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7327', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7328', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7329', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7330', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7331', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7332', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7333', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7359', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7361', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7363', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7494', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7548', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7549', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7567', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7568', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7577', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7579', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7583', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7587', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7593', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7595', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7598', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7604', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7605', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7612', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7613', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7614', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7615', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10044', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10045', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10046', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10047', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10048', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10049', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10050', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10051', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10054', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10055', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10056', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10057', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10058', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10059', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10060', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10061', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10062', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10063', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10066', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10067', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10068', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10069', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10074', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10075', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10077', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10079', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10082', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10083', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10084', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10085', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10086', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10087', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10090', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10091', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10095', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10099', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10133', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10173', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10184', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10185', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10187', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10189', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10218', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10219', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10220', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10221', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10243', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10279', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10285', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10286', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10290', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10293', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10294', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10296', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10306', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10388', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10399', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10400', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10409', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10410', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10412', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10414', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10415', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10416', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10417', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10422', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10423', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10424', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10425', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10450', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10451', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10462', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10463', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10543', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10544', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10545', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10546', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10547', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '10548', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '12681', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '12801', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13163', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13164', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13185', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13186', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13189', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13190', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13191', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13192', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13193', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13195', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13196', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13197', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13200', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13201', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13202', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13203', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13204', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13206', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13243', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13244', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13245', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13246', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13247', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13393', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '13394', '0', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '128', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '17729', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '17730', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '17945', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '23481', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '17947', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '23482', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '17949', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '23483', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '20397', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '20318', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '20319', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '20321', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '27252', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '27256', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('0', '28170', '8', '', '', 'Spell for deprecated item');
INSERT IGNORE INTO `disables` VALUES ('4', '8839', '0', '', '', 'Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('4', '9161', '0', '', '', 'Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('4', '9162', '0', '', '', 'Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('4', '9163', '0', '', '', 'Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('4', '9164', '0', '', '', 'Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('4', '4961', '0', '', '', '5v5 Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('4', '4960', '0', '', '', '3v3 Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('4', '4959', '0', '', '', '2v2 Arena Honorable Kills');
INSERT IGNORE INTO `disables` VALUES ('0', '32314', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '7704', '0', '', '', 'Vehicular Gnomeslaughter');
INSERT IGNORE INTO `disables` VALUES ('4', '7705', '0', '', '', 'Vehicular Gnomeslaughter');
INSERT IGNORE INTO `disables` VALUES ('4', '7706', '0', '', '', 'Vehicular Gnomeslaughter');
INSERT IGNORE INTO `disables` VALUES ('4', '7707', '0', '', '', 'Vehicular Gnomeslaughter');
INSERT IGNORE INTO `disables` VALUES ('4', '7708', '0', '', '', 'Vehicular Gnomeslaughter');
INSERT IGNORE INTO `disables` VALUES ('4', '11491', '0', '', '', 'Isle of Conquest All-Star');
INSERT IGNORE INTO `disables` VALUES ('0', '758', '8', '', '', 'Spell for deprecated item 1254');
INSERT IGNORE INTO `disables` VALUES ('0', '23480', '8', '', '', 'Spell for deprecated item 1254');
INSERT IGNORE INTO `disables` VALUES ('0', '62973', '1', '', '', 'mech');
INSERT IGNORE INTO `disables` VALUES ('0', '63388', '1', '', '', 'Rubaxa');
INSERT IGNORE INTO `disables` VALUES ('3', '11', '0', '', '', 'The Ring of Valor');
INSERT IGNORE INTO `disables` VALUES ('0', '38177', '1', '', '', '???? ??? ????? ?????? ????????');
INSERT IGNORE INTO `disables` VALUES ('0', '51804', '8', '', '', 'Power Siphon');
INSERT IGNORE INTO `disables` VALUES ('0', '698', '49', '489,529,529,566', '4572,4571,3417,3418,3820', 'Ritual of Summoning spell on BG');
INSERT IGNORE INTO `disables` VALUES ('0', '86425', '1', '', '', 'bug');
INSERT IGNORE INTO `disables` VALUES ('0', '74087', '1', '', '', 'bug');
INSERT IGNORE INTO `disables` VALUES ('0', '80987', '1', '', '', 'bug');
INSERT IGNORE INTO `disables` VALUES ('0', '93392', '1', '', '', 'bug');
INSERT IGNORE INTO `disables` VALUES ('0', '75554', '1', '', '', 'bug');
INSERT IGNORE INTO `disables` VALUES ('0', '51292', '8', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '77606', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '65455', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '92052', '8', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '51291', '8', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '33332', '1', '', '', 'bug');
INSERT IGNORE INTO `disables` VALUES ('0', '16615', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '16614', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '7714', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '7721', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '60100', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '81099', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '47394', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '87368', '1', '', '', 'tailor bug duh');
INSERT IGNORE INTO `disables` VALUES ('0', '78337', '1', '', '', '200% Damage');
INSERT IGNORE INTO `disables` VALUES ('0', '75701', '2', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '47360', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '46010', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('4', '15673', '0', '', '', 'Chogall');
INSERT IGNORE INTO `disables` VALUES ('4', '16025', '0', '', '', 'Sinestra');
INSERT IGNORE INTO `disables` VALUES ('4', '15672', '0', '', '', 'Valiona');
INSERT IGNORE INTO `disables` VALUES ('4', '15094', '0', '', '', 'Halfus');
INSERT IGNORE INTO `disables` VALUES ('4', '15472', '0', '', '', 'Sinestra');
INSERT IGNORE INTO `disables` VALUES ('4', '15471', '0', '', '', 'Ascendant Council');
INSERT IGNORE INTO `disables` VALUES ('4', '15666', '0', '', '', 'Sinestra');
INSERT IGNORE INTO `disables` VALUES ('4', '16014', '0', '', '', 'Maloriak');
INSERT IGNORE INTO `disables` VALUES ('4', '15651', '0', '', '', 'Omontron');
INSERT IGNORE INTO `disables` VALUES ('4', '15652', '0', '', '', 'Omnotron');
INSERT IGNORE INTO `disables` VALUES ('4', '15653', '0', '', '', 'Omnotron');
INSERT IGNORE INTO `disables` VALUES ('4', '15654', '0', '', '', 'Omnotron');
INSERT IGNORE INTO `disables` VALUES ('4', '15655', '0', '', '', 'Atramedes');
INSERT IGNORE INTO `disables` VALUES ('4', '15650', '0', '', '', 'Magmaw');
INSERT IGNORE INTO `disables` VALUES ('4', '16002', '0', '', '', 'Chimaeron');
INSERT IGNORE INTO `disables` VALUES ('4', '15427', '0', '', '', 'guild 25');
INSERT IGNORE INTO `disables` VALUES ('0', '88797', '1', '', '', '');
INSERT IGNORE INTO `disables` VALUES ('0', '59710', '1', '', '', '');