INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '669', 'Language Orcish');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '81', 'Dodge');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '107', 'Block');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '198', 'One-Handed Maces');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '203', 'Unarmed');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '204', 'Defense');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '227', 'Staves');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '403', 'Lightning Bolt');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '522', 'SPELLDEFENSE (DND)');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '1843', 'Disarm');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '2382', 'Generic');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '2479', 'Honorless Target');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '3050', 'Detect');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '3365', 'Opening');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '6233', 'Closing');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '6246', 'Closing');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '6247', 'Opening');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '6477', 'Opening');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '6478', 'Opening');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '6603', 'Attack');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '7266', 'Duel');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '7267', 'Grovel');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '7355', 'Stuck');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '8386', 'Attacking');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '9077', 'Leather');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '9078', 'Cloth');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '9116', 'Shields');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '9125', 'Generic');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '20549', 'War Stomp');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '20550', 'Endurance');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '20551', 'Nature Resistance');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '20552', 'Cultivation');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '21651', 'Opening');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '21652', 'Closing');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '22027', 'Remove Insignia');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '22810', 'Opening - No Text');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '27763', 'Relic - Totem');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '45927', 'Summon Friend');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '61437', 'Opening');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '1180', 'Daggers');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '15590', 'Fist Weapons');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '196', 'One-Handed Axes');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '197', 'Two-Handed Axes');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '199', 'Two-Handed Maces');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '76296', 'Weapon Skills');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '76272', 'Armor Skills');
INSERT INTO `playercreateinfo_spell` VALUES ('6', '7', '670', 'Language Taurahe');
